#!/bin/bash
cd $(dirname "${0}")

MOD="${1}"
VERSION="${2}"
if [ -z "${MOD}" ] || [ -z "${VERSION}" ]; then
	echo "Usage: ${0} <mod name> <version>"
	exit
fi

if ! [ -f "./modtools.json" ]; then
	echo modtools.json is missing. For instructions about how to set it up, please visit:
	echo https://github.com/quarantin/pz-modding-tools/blob/main/tools/config/README.md
	exit
fi

MODNAME=$(jq -r ".${MOD}.name" ./modtools.json)
MODREPO=$(jq -r ".${MOD}.repo" ./modtools.json)
if [ "${MODNAME}" = "null" ] || [ "${MODREPO}" = "null" ]; then
	echo "Unknown mod \`${MOD}\`. You might have to add it to modtools.json"
	exit
fi

cd "${MODREPO}"

ZOMBOID="${HOME}/Zomboid"

# Export mod to workshop folder
TARGET="${ZOMBOID}/Workshop/${MOD}/Contents/mods/${MOD}/"
mkdir -p "${TARGET}"
rm -rf "${TARGET}"
git checkout-index -a -f --prefix="${TARGET}"

# Updating version for mod.info
MODINFO="mod.info"
cd "${TARGET}"
sed -i "s/^name=${MODNAME}.*/name=${MODNAME} (v${VERSION})/" "${MODINFO}"
unix2dos -q "${MODINFO}"
find . -iname '*.utf8.txt' -delete
echo $(pwd)
rm -f README.md TODO .gitignore Makefile LICENSE

# Updating version for workshop.txt
cd "${ZOMBOID}/Workshop/${MOD}"
mv "${TARGET}/preview.png" .
mv "${TARGET}/workshop.txt" .
sed -i "s/^version=.*$/version=${VERSION}/" workshop.txt
sed -i "s/^description=Latest version:.*$/description=Latest version: ${VERSION}/" workshop.txt

# Creating release tarball and zip file
cd "${TARGET}"
cd ..
DIST="${MODREPO}/dist"
TARBALL="${DIST}/${MOD}-${VERSION}.tar.xz"
ZIPFILE="${DIST}/${MOD}-${VERSION}.zip"
mkdir -p "${DIST}"
rm -f "${TARBALL}" "${ZIPFILE}"
tar cvjf "${TARBALL}" *
zip -r "${ZIPFILE}" *
