#!/bin/bash
cd $(dirname ${0})
. zconf

mv "${ZOMBOID_BACKUP}" "${ZOMBOID_BACKUP}.${DATE}"
cp -a "${ZOMBOID_SAVE}" "${ZOMBOID_BACKUP}"
date
notify-send -u normal -t 10000 -i info 'Zomboid' 'Game Saved Successfully'
